name: Automatic Release Creation

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update module.json Version and Download URL
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          node -e "
            const fs = require('fs');
            const tag = process.env.TAG_NAME;
            const version = tag.replace(/^v/, '');
            const manifest = JSON.parse(fs.readFileSync('module.json'));

            manifest.version = version;
            manifest.download = \`https://github.com/\${process.env.GITHUB_REPOSITORY}/releases/download/\${tag}/module.zip\`;

            fs.writeFileSync('module.json', JSON.stringify(manifest, null, 2));
            console.log(\`module.json actualizado automáticamente a la versión \${version} para el tag \${tag}\`);
          "

      - name: Create Module Zip
        run: |
          zip -r ./module.zip . -x "*.git*" "*.github*" "*.LOCK" ".gitignore" ".gitattributes"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            module.json
            module.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}